<a href="https://colab.research.google.com/github/vaishnavi-3969/Deep-Learning/blob/main/Backpropagation_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import pandas as pd

In [50]:
df = pd.DataFrame(
    [[8,8,4],[7,9,5],[5,12,7],[6,10,6]],
    columns = ['cgpa','profile_score','lpa']
)

In [51]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     5             12    7
3     6             10    6

In [52]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):
    parameters['W'+str(l)] = np.ones((layer_dims[l-1], layer_dims[l])) * 0.1
    parameters['b'+str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [53]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [54]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T,A_prev) + b
  return Z

In [55]:
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L + 1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print('A' + str(l-1) + ": ", A_prev)
    print("W" + str(l)+": ",Wl)
    print("b" + str(l) + ": ",bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A" + str(l) + ": ", A)
    print("**" * 20)

  return A, A_prev

In [56]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

# parameter initialization
parameters = initialize_parameters([2,2,1])

In [57]:
L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [58]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [59]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat, A1 = L_layer_forward(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [60]:
y_hat = y_hat[0][0]

In [61]:
A1

array([[1.6],
       [1.6]])

In [62]:
y_hat

0.32000000000000006

In [63]:
update_parameters(parameters, y, y_hat, A1, X)

In [64]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [65]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]

y_hat, A1 = L_layer_forward(X,parameters)

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************


In [66]:
update_parameters(parameters, y, y_hat, A1, X)

<ipython-input-58-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-58-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-58-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [67]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1)
y = df[['lpa']].values[2][0]

y_hat, A1 = L_layer_forward(X,parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.949989  ]
 [1.98888586]]
****************************************
A1:  [[1.949989  ]
 [1.98888586]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
----------------------------------------
A2:  [[0.63687445]]
****************************************


In [68]:
update_parameters(parameters, y, y_hat, A1, X)

<ipython-input-58-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-58-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-58-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [69]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1)
y = df[['lpa']].values[3][0]

y_hat, A1 = L_layer_forward(X,parameters)

A0:  [[ 6]
 [10]]
W1:  [[0.12425802 0.14008193]
 [0.12428952 0.14015752]]
b1:  [[0.00390039]
 [0.00390669]]
----------------------------------------
A1:  [[1.99234367]
 [2.2459735 ]]
****************************************
A1:  [[1.99234367]
 [2.2459735 ]]
W2:  [[0.15194532]
 [0.15244033]]
b2:  [[0.16516658]]
----------------------------------------
A2:  [[0.8102708]]
****************************************


In [70]:
update_parameters(parameters, y, y_hat, A1, X)

<ipython-input-58-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-58-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-58-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [71]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.949989  ]
 [1.98888586]]
****************************************
A1:  [[1.949989  ]
 [1.98888586]]
W2:  [[0.12712927]
 [0.127

{'W1': array([[0.26326273, 0.38317373],
        [0.27669851, 0.40805436]]),
 'b1': array([[0.02721036],
        [0.02953751]]),
 'W2': array([[0.40836907],
        [0.48104203]]),
 'b2': array([[0.48272968]])}

In [72]:
parameters

{'W1': array([[0.26326273, 0.38317373],
        [0.27669851, 0.40805436]]),
 'b1': array([[0.02721036],
        [0.02953751]]),
 'W2': array([[0.40836907],
        [0.48104203]]),
 'b2': array([[0.48272968]])}